#!/usr/bin/env python3
"""Apply symbol renames produced by build_rename_map.py.

Usage: rename_syms.py <file>  (edits the file in place)
"""
import sys, re

PAIRS = [
    ('AS_UNFNC', 'MS_FUNDSP'),
    ('AS_M_NEG', 'MS_NEGTAB'),
    ('AS_MEQUU', 'MS_NOTTAB'),
    ('AS_M_REL', 'MS_PTDORL'),
    ('AS_TOKEN_NAME_TABLE', 'MS_RESLST'),
    ('AS_ERROR_MESSAGES', 'MS_ERRTAB'),
    ('AS_QT_ERROR', 'MS_ERR'),
    ('AS_QT_IN', 'MS_INTXT'),
    ('AS_QT_BREAK', 'MS_BRKTXT'),
    ('AS_GTFORPNT', 'MS_FNDFOR'),
    ('AS_L_GTFORPNT_1', 'MS_FFLOOP'),
    ('AS_L_GTFORPNT_2', 'MS_CMPFOR'),
    ('AS_L_GTFORPNT_3', 'MS_ADDFRS'),
    ('AS_L_GTFORPNT_4', 'MS_FFRTS'),
    ('AS_BLTU', 'MS_BLTU'),
    ('AS_BLTU2', 'MS_BLTUC'),
    ('AS_L_BLTU2_1', 'MS_BLT1'),
    ('AS_L_BLTU2_2', 'MS_BLTLP'),
    ('AS_L_BLTU2_3', 'MS_MOREN1'),
    ('AS_L_BLTU2_4', 'MS_DECBLT'),
    ('AS_CHKMEM', 'MS_GETSTK'),
    ('AS_REASON', 'MS_REASON'),
    ('AS_L_REASON_1', 'MS_TRYMOR'),
    ('AS_L_REASON_2', 'MS_REASAV'),
    ('AS_L_REASON_3', 'MS_REASTO'),
    ('AS_L_REASON_4', 'MS_REARTS'),
    ('AS_MEMERR', 'MS_OMERR'),
    ('AS_ERROR', 'MS_ERROR'),
    ('AS_L_ERROR_1', 'MS_ERRCRD'),
    ('AS_L_ERROR_2', 'MS_GETERR'),
    ('AS_PRINT_ERROR_LINNUM', 'MS_ERRFIN'),
    ('AS_RESTART', 'MS_MAIN'),
    ('AS_NUMBERED_LINE', 'MS_MAIN1'),
    ('AS_L_NUMBERED_LINE_1', 'MS_QDECT1'),
    ('AS_L_NUMBERED_LINE_2', 'MS_MLOOP'),
    ('AS_PUT_NEW_LINE', 'MS_NODEL'),
    ('AS_L_PUT_NEW_LINE_1', 'MS_NODELC'),
    ('AS_L_PUT_NEW_LINE_2', 'MS_STOLOP'),
    ('AS_INLIN', 'MS_INLIN'),
    ('AS_INLIN2', 'MS_INLIN2'),
    ('AS_L_INLIN2_1', 'MS_GDBUFS'),
    ('AS_L_INLIN2_2', 'MS_LOPBHT'),
    ('AS_L_INLIN2_3', 'MS_NOCHR'),
    ('AS_PARSE_INPUT_LINE', 'MS_CRUNCH'),
    ('AS_L_PARSE_3', 'MS_KLOOP1'),
    ('AS_L_PARSE_4', 'MS_MUSTCR'),
    ('AS_L_PARSE_5', 'MS_RESER'),
    ('AS_L_PARSE_8', 'MS_GETBPT'),
    ('AS_L_PARSE_9', 'MS_STUFFH'),
    ('AS_L_PARSE_10', 'MS_COLIS'),
    ('AS_L_PARSE_11', 'MS_NODATT'),
    ('AS_L_PARSE_13', 'MS_STRNG'),
    ('AS_L_PARSE_14', 'MS_NTHIS'),
    ('AS_L_PARSE_17', 'MS_CRDONE'),
    ('AS_FNDLIN', 'MS_FNDLIN'),
    ('AS_FL1', 'MS_FNDLNC'),
    ('AS_L_FL1_1', 'MS_FNDLO1'),
    ('AS_L_FL1_2', 'MS_AFFRTS'),
    ('AS_L_FL1_3', 'MS_FLINRT'),
    ('AS_RTS_1', 'MS_FLNRTS'),
    ('AS_NEW', 'MS_SCRATH'),
    ('AS_SCRTCH', 'MS_SCRTCH'),
    ('AS_SETPTRS', 'MS_RUNC'),
    ('AS_CLEAR', 'MS_CLEAR'),
    ('AS_CLEARC', 'MS_CLEARC'),
    ('AS_STKINI', 'MS_STKINI'),
    ('AS_RTS_2', 'MS_STKRTS'),
    ('AS_STXTPT', 'MS_STXTPT'),
    ('AS_LIST', 'MS_LIST'),
    ('AS_L_LIST_1', 'MS_GOLST'),
    ('AS_L_LIST_3', 'MS_LSTEND'),
    ('AS_LIST_0', 'MS_LIST4'),
    ('AS_L_LIST_0_5', 'MS_TSTDUN'),
    ('AS_L_LIST_0_6', 'MS_TYPLIN'),
    ('AS_LIST_1', 'MS_PRIT4'),
    ('AS_LIST_2', 'MS_PLOOP'),
    ('AS_L_LIST_4_1', 'MS_RESRCH'),
    ('AS_L_LIST_4_3', 'MS_PRIT3'),
    ('AS_FOR', 'MS_FOR'),
    ('AS_L_FOR_1', 'MS_NOTOL'),
    ('AS_STEP', 'MS_LDFONE'),
    ('AS_RESTORE', 'MS_RESTOR'),
    ('AS_ISCNTC', 'MS_ISCNTC'),
    ('AS_STOP', 'MS_STOP'),
    ('AS_CONT', 'MS_CONT'),
    ('AS_RUN', 'MS_RUN'),
    ('AS_GOSUB', 'MS_GOSUB'),
    ('AS_GOTO', 'MS_GOTO'),
    ('AS_DATA', 'MS_DATA'),
    ('AS_DATAN', 'MS_DATAN'),
    ('AS_IF', 'MS_IF'),
    ('AS_REM', 'MS_REM'),
    ('AS_ONGOTO', 'MS_ONGOTO'),
    ('AS_LINGET', 'MS_LINGET'),
    ('AS_LET', 'MS_LET'),
    ('AS_PRINT', 'MS_PRINT'),
    ('AS_CRDO', 'MS_CRDO'),
    ('AS_OUTQUES', 'MS_OUTQST'),
    ('AS_OUTDO', 'MS_OUTDO'),
    ('AS_GET', 'MS_GET'),
    ('AS_INPUT', 'MS_INPUT'),
    ('AS_READ', 'MS_READ'),
    ('AS_NEXT', 'MS_NEXT'),
    ('AS_NEXT_1', 'MS_NEXT_1'),
    ('AS_NEXT_2', 'MS_NEXT_2'),
    ('AS_NEXT_3', 'MS_NEXT_3'),
    ('AS_EQUOP', 'MS_NOTOP'),
    ('AS_OR', 'MS_OROP'),
    ('AS_ANDOP', 'MS_ANDOP'),
    ('AS_RELOPS', 'MS_DOREL'),
    ('AS_DIM', 'MS_DIM'),
    ('AS_FRE', 'MS_FRE'),
    ('AS_POS', 'MS_POS'),
    ('AS_DEF', 'MS_DEF'),
    ('AS_STR', 'MS_STR'),
    ('AS_GARBAG', 'MS_GARBA2'),
    ('AS_CHRSTR', 'MS_CHR'),
    ('AS_LEFTSTR', 'MS_LEFT'),
    ('AS_RIGHTSTR', 'MS_RIGHT'),
    ('AS_MIDSTR', 'MS_MID'),
    ('AS_LEN', 'MS_LEN'),
    ('AS_ASC', 'MS_ASC'),
    ('AS_VAL', 'MS_VAL'),
    ('AS_PEEK', 'MS_PEEK'),
    ('AS_POKE', 'MS_POKE'),
    ('AS_WAIT', 'MS_FNWAIT'),
    ('AS_FSUBT', 'MS_FSUBT'),
    ('AS_FADDT', 'MS_FADDT'),
    ('AS_CON_ONE', 'MS_FONE'),
    ('AS_LOG', 'MS_LOG'),
    ('AS_FMULTT', 'MS_FMULTT'),
    ('AS_FDIVT', 'MS_FDIVT'),
    ('AS_SGN', 'MS_SGN'),
    ('AS_ABS', 'MS_ABS'),
    ('AS_INT', 'MS_INT'),
    ('AS_INPRT', 'MS_INPRT'),
    ('AS_LINPRT', 'MS_LINPRT'),
    ('AS_SQR', 'MS_SQR'),
    ('AS_FPWRT', 'MS_FPWRT'),
    ('AS_NEGOP', 'MS_NEGOP'),
    ('AS_EXP', 'MS_EXP'),
    ('AS_RND', 'MS_RND'),
    ('AS_COS', 'MS_COS'),
    ('AS_SIN', 'MS_SIN'),
    ('AS_TAN', 'MS_TAN'),
    ('AS_ATN', 'MS_ATN'),
]

if len(sys.argv) < 2:
    print(f"Usage: {sys.argv[0]} <file>", file=sys.stderr)
    sys.exit(1)

path = sys.argv[1]
with open(path) as f:
    text = f.read()

for old, new in PAIRS:
    text = re.sub('\\b' + re.escape(old) + '\\b', new, text)

with open(path, 'w') as f:
    f.write(text)

